server:
  port: 8086
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/mysql?useSSL=false&serverTimezone=Asia/Shanghai
  jackson:
    serialization:
      indent-output: true
mybatis:
  type-aliases-package: com.newer.springbootpage.domain
  mapper-locations: classpath:com/newer/springbootpage/mapper/*.xml




